return {
  "nvim-treesitter/nvim-treesitter",

  opts = {
    ensure_installed = {
      "bash",
      "comment",
      "css",
      "csv",
      "desktop",
      "diff",
      "dockerfile",
      "dot",
      "editorconfig",
      "fish",
      "gdscript",
      "gdshader",
      "godot_resource",
      "gitcommit",
      "git_config",
      "gitignore",
      "git_rebase",
      "go",
      "gpg",
      "graphql",
      "hcl",
      "html",
      "http",
      "ini",
      "javascript",
      "json",
      "jsonc",
      "latex",
      "lua",
      "luadoc",
      "luap",
      "markdown",
      "markdown_inline",
      "matlab",
      "nginx",
      "nix",
      "nu",
      "php",
      "printf",
      "prisma",
      "properties",
      "powershell",
      "python",
      "regex",
      "ruby",
      "rust",
      "sql",
      "superhtml",
      "svelte",
      "toml",
      "tsx",
      "typescript",
      "typst",
      "udev",
      "vim",
      "vimdoc",
      "yaml",
    },
    highlight = { enable = true, use_languagetree = true },
    indent = { enable = true },
  },
  main = "nvim-treesitter.configs",
  build = ":TSUpdate",

  event = { "BufReadPost", "BufNewFile" },
  cmd = { "TSInstall", "TSBufEnable", "TSBufDisable", "TSModuleInfo" },
}
